// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type Request struct {
	BizType int    `json:"biz_type" validate:"required"`
	TaskId  string `json:"task_id,optional"`
	Start   int64  `json:"start,optional"`
	End     int64  `json:"end,optional"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
