// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddCronCycleTaskReq struct {
	CronCycleTask
}

type AddFixedTimeSingleTaskReq struct {
	FixedTimeSingleTask
}

type AddRealTimeSingleTaskReq struct {
	RealTimeSingleTask
}

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type BaseData struct {
	Id     string `json:"id"`
	Status int64  `json:"status"`
}

type CronCycleTask struct {
	Type     int64  `json:"type" validate:"required,min=1,max=3"`
	BizCode  string `json:"biz_code" validate:"required"`
	Cron     string `json:"cron" validate:"required"`
	ExecPath string `json:"exec_path" validate:"required"`
	Param    string `json:"param" validate:"required"`
	Timeout  int64  `json:"timeout" validate:"required,min=5"`
	ExtInfo  string `json:"ext_info,optional"`
}

type CronCycleTaskData struct {
	BaseData
	CronCycleTask
}

type DelCronCycleTaskReq struct {
	Id string `json:"id" validate:"required"`
}

type DelFixedTimeSingleTaskReq struct {
	Id string `json:"id" validate:"required"`
}

type FixedTimeSingleTask struct {
	Type     int64  `json:"type" validate:"required,min=1,max=3"`
	BizCode  string `json:"biz_code" validate:"required"`
	BizId    string `json:"biz_id,optional"`
	ExecPath string `json:"exec_path" validate:"required"`
	ExecTime int64  `json:"exec_time" validate:"required"`
	Param    string `json:"param" validate:"required"`
	Timeout  int64  `json:"timeout" validate:"required,min=5"`
	ExtInfo  string `json:"ext_info,optional"`
}

type FixedTimeSingleTaskData struct {
	BaseData
	FixedTimeSingleTask
	StartTime  string `json:"start_time"`
	FinishTime string `json:"finish_time"`
	Interval   int64  `json:"interval"`
	ResultMsg  string `json:"result_msg"`
}

type ModCronCycleTaskReq struct {
	Id string `json:"id" validate:"required"`
	CronCycleTask
}

type PostDemo struct {
	Name           string `json:"name" validate:"required"`                           // 姓名
	Age            int64  `json:"age" validate:"required,gte=1,lte=130"`              // 年龄
	Mobile         string `json:"mobile,optional" validate:"omitempty,checkMobile"`   // 手机号码
	Email          string `json:"email,optional" validate:"omitempty,checkEmail"`     // 邮箱地址
	Date           string `json:"date" validate:"omitempty,checkDate,checkAfterDate"` // 时间
	Password       string `json:"password" validate:"required"`                       // 密码
	ConfimPassword string `json:"confimPassword" validate:"eqfield=Password"`         // 确认密码
}

type PostDemoReq struct {
	PostDemo
}

type QueryCronCycleTaskReq struct {
	Id string `json:"id,optional"`
}

type QueryFixedTimeSingleTaskReq struct {
	Id          string `json:"id,optional"`
	Status      int64  `json:"status,optional"`
	TimeHorizon int64  `json:"time_horizon,optional"`
	Limit       int64  `json:"limit,optional"`
}

type QueryFixedTimeSingleTaskResp struct {
	Base
	Data []FixedTimeSingleTaskData `json:"data"`
}

type QueryRealTimeSingleTaskReq struct {
	Id          string `json:"id,optional"`
	Status      int64  `json:"status,optional"`
	TimeHorizon int64  `json:"time_horizon,optional"`
	Limit       int64  `json:"limit,optional"`
}

type QueryRealTimeSingleTaskResp struct {
	Base
	Data []RealTimeSingleTaskData `json:"data"`
}

type QueryTaskConfigResp struct {
	Base
	Data []CronCycleTaskData `json:"data"`
}

type RealTimeSingleTask struct {
	Type     int64  `json:"type" validate:"required,min=1,max=3"`
	BizCode  string `json:"biz_code" validate:"required"`
	BizId    string `json:"biz_id,optional"`
	ExecPath string `json:"exec_path" validate:"required"`
	Param    string `json:"param" validate:"required"`
	Timeout  int64  `json:"timeout" validate:"required,min=5"`
	ExtInfo  string `json:"ext_info,optional"`
}

type RealTimeSingleTaskData struct {
	BaseData
	RealTimeSingleTask
	StartTime  string `json:"start_time"`
	FinishTime string `json:"finish_time"`
	Interval   int64  `json:"interval"`
	ResultMsg  string `json:"result_msg"`
}

type Response struct {
	Base
}

type StartOrStopCronCycleTaskReq struct {
	Id      string `json:"id" validate:"required"`
	IsStart bool   `json:"is_start"`
}
